### ISSUE TITLE
ProjectServ: Allow searching for projects by namespaces

### ISSUE THREAD

**Issue by xnrand** [freenode/atheme-fn#12]
Mainly by cloak namespaces. For instance, a command like `/msg ProjectServ LISTCLOAK f*` would list all projects with a cloak namespace starting with `f`, such as freenode with the `freenode/*` namespace.

Searching by channel namespaces would only be useful in edge cases where there exist no registered channels in a namespace (so ChanServ `LIST` and `INFO` don't help)

**Comment by ilbelkyr** [comment]
@glguy did the hard work on this in #9 already, it seems (thank you!). That addresses the `LISTCLOAK` part; I've added a module providing `LISTCHANNEL` as well but it's basically just the `LISTCLOAK` code with the appropriate things changed.

(While I agree `LISTCHANNEL` isn't nearly as important, it does make sense in the edge cases you mentioned. It also avoids having to take an extra step via ChanServ when it's really ProjectServ info you're after.)
