### ISSUE TITLE
Add a NS VHOST similar command that can be used by GCs with their group prefixes

### ISSUE THREAD

**Issue by danilomac** [freenode/atheme-fn#3]
I suggest to add a command similar to /NS VHOST that works for group contacts.

It can work by checking in a flie/DB if the user that is triggering the command is a group contact, and checking if the cloak that the GC is attempting to add/remove have a prefix of that group. After that, it can work like NS VHOST.

Example: `/NS CLOAK <account> ON <group_prefix/something>`

With this command the GCs will can manage the group cloaks by themselves and reduce the staffs work.

Another suggestion is create a group of trusted users that can use this command to add unaffiliated cloaks, so these users can help to give unaffiliated cloaks when no staff is online.

**Comment by bigpresh** [comment]
This has been suggested before, but it was decided that we prefer the personal touch, and the ability to help suggest sensible cloaks etc, so I think it's unlikely to be implemented.

However, thank you for the suggestion!
